server {
    listen 80;
    
    # Esto carga tu interfaz visual normal
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Esto actúa como puente secreto hacia Chatwoot saltándose el CORS
    location /chatwoot-api/ {
        proxy_pass https://chatwoot.method.cl/;
        proxy_ssl_server_name on;
        
        # Cabeceras para que el navegador confíe ciegamente
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, api_access_token';
        
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }
}
