server {
    listen 3000;
    
    # ESTA ES LA LÍNEA MÁGICA QUE FALTA:
    underscores_in_headers on;
    
    # Carga tu interfaz visual normal (el React)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # El puente secreto hacia Chatwoot
    location /chatwoot-api/ {
        proxy_pass https://chatwoot.method.cl/;
        proxy_ssl_server_name on;
        
        # Le decimos al navegador que confíe
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, api_access_token';
        
        # Responde rápido a las peticiones previas (preflight)
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }
}
